### ISSUE TITLE
Navbar texts are not capitalized and missing hover effects.

### ISSUE THREAD

**Issue by yuvaraj-LR** [cn10xdev/Event-Management#35]

**Comment by yuvaraj-LR** [comment]
@bhardwajdisha - The navbar design didn't look appealing with the lower-case text and without any hover effects. To improve it, I have updated the text styling and added hover animations. The changes are linked in a pull request.

Old Design (without capitalized text and hover animations):
![Screenshot from 2024-09-27 00-23-25](https://github.com/user-attachments/assets/9e7369ee-77ce-4c26-8eb1-05963ae05457)

Updated Design (with capitalized text and hover animations):
![Screenshot from 2024-09-27 00-29-35](https://github.com/user-attachments/assets/a46aa214-25c3-49c1-a5f6-733b43fd48ac)

PR - #3

**Comment by bhardwajdisha** [comment]
Good observation and enhancements
